# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyenv < Formula
  desc "TUI for managing .env files"
  homepage "https://lazynop.github.io/lazyenv/"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lazynop/lazyenv/releases/download/v0.6.0/lazyenv_0.6.0_darwin_amd64.tar.gz"
      sha256 "e55ec7707a2b637fc5af4302c4b2d421ef920a1c2336bda88cec827fd4aa06d3"

      define_method(:install) do
        bin.install "lazyenv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lazynop/lazyenv/releases/download/v0.6.0/lazyenv_0.6.0_darwin_arm64.tar.gz"
      sha256 "52a13051e846cff189a569a147905f97ab42a07cc65779704622355534e698ef"

      define_method(:install) do
        bin.install "lazyenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lazynop/lazyenv/releases/download/v0.6.0/lazyenv_0.6.0_linux_amd64.tar.gz"
      sha256 "f5cd6bd9d7a6a3eef92fdb16cfd9a71381aabe10f0e4de8caa3071f213ef678b"
      define_method(:install) do
        bin.install "lazyenv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lazynop/lazyenv/releases/download/v0.6.0/lazyenv_0.6.0_linux_arm64.tar.gz"
      sha256 "7bae91ccf96256150c6b7e37d78e8b88b2555f8c8962aed74c6eec4fa32b6265"
      define_method(:install) do
        bin.install "lazyenv"
      end
    end
  end

  test do
    system bin/"lazyenv", "--version"
  end
end
