# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyenv < Formula
  desc "TUI for managing .env files"
  homepage "https://lazynop.github.io/lazyenv/"
  version "0.4.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lazynop/lazyenv/releases/download/v0.4.3/lazyenv_0.4.3_darwin_amd64.tar.gz"
      sha256 "e0a82a563638de35a4d0ac8ec4e84a83126046fe6a39e9838d9e8552f60a0fac"

      define_method(:install) do
        bin.install "lazyenv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lazynop/lazyenv/releases/download/v0.4.3/lazyenv_0.4.3_darwin_arm64.tar.gz"
      sha256 "f0cff5471168931df3443a21f173464c2598da387e078f12ac61747726b6dd48"

      define_method(:install) do
        bin.install "lazyenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lazynop/lazyenv/releases/download/v0.4.3/lazyenv_0.4.3_linux_amd64.tar.gz"
      sha256 "0f020f9516370e90240c30e4c96ea3eef7812b9373ffc734649410374d1740b1"
      define_method(:install) do
        bin.install "lazyenv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lazynop/lazyenv/releases/download/v0.4.3/lazyenv_0.4.3_linux_arm64.tar.gz"
      sha256 "6536187ae6d38037d3cc964de0da2bd5fc0dd88415af7fdbab96302aef2cafb8"
      define_method(:install) do
        bin.install "lazyenv"
      end
    end
  end

  test do
    system bin/"lazyenv", "--version"
  end
end
