# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyenv < Formula
  desc "TUI for managing .env files"
  homepage "https://lazynop.github.io/lazyenv/"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lazynop/lazyenv/releases/download/v0.9.0/lazyenv_0.9.0_darwin_amd64.tar.gz"
      sha256 "aaba0d1b3a4d678c7f8813d2d4e6d29e44a44f7fd3cd88602a85173abbac3330"

      define_method(:install) do
        bin.install "lazyenv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lazynop/lazyenv/releases/download/v0.9.0/lazyenv_0.9.0_darwin_arm64.tar.gz"
      sha256 "f553b94b915a4c4557dde410144a425b0d06ac89878d4853e3d068ebc549f930"

      define_method(:install) do
        bin.install "lazyenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lazynop/lazyenv/releases/download/v0.9.0/lazyenv_0.9.0_linux_amd64.tar.gz"
      sha256 "d94c5c13f8f3f686911c77e23f8afcf2f4c136fbf1285c95c8b4c22f24ef8fb8"
      define_method(:install) do
        bin.install "lazyenv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lazynop/lazyenv/releases/download/v0.9.0/lazyenv_0.9.0_linux_arm64.tar.gz"
      sha256 "4a85eec015317702bc6d3d5ed860f9b01c2c490f67b556a76abc4a62badfb0f2"
      define_method(:install) do
        bin.install "lazyenv"
      end
    end
  end

  test do
    system bin/"lazyenv", "--version"
  end
end
